apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hdl-library-adaptive_nulling
  title: ADAPTIVE_NULLING HDL IP core
  description: ADAPTIVE_NULLING HDL IP core
  version: main
  classification: software
  license:
  - ADI BSD License
  annotations:
    backstage.io/source-location: url:https://github.com/gncemre23/hdl/tree/main/library/adaptive_nulling
  tags:
  - hdl
  - ip-core
  - library
  links: []
spec:
  owner: group:default/hdl-sw-team
  type: source
  lifecycle: sustain
